data_path:
  - /home/campbell/yulee/DAMM/new/data/
res_path:
  - '/home/campbell/yulee/DAMM/new/res/'
#cohort:
#  - eddy # eddy, meta, basel
experiment_id:
  - 1
sample_size:
  - 10
plausibility_markers:
  eddy:
    positive:
      - [CD3, CD4]
      - [CD3, CD8]
      - [CD45, CD3]
      - [CD45, CD4]
      - [CD45, CD8]
      - [CD45, CD20]
      - [CD45, CD68]
    negative:
      - [CD3, CD20]
      - [CD3, CD31]
      - [CD3, CD68]
      - [CD3, ECadherin]
      - [CD4, CD8]
      - [CD4, CD20]
      - [CD4, CD31]
      - [CD4, ECadherin]
      - [CD8, CD20]
      - [CD8, CD31]
      - [CD8, CD68]
      - [CD8, ECadherin]
      - [CD20, CD31]
      - [CD20, CD68]
      - [CD20, ECadherin]
      - [CD31, CD68]
      - [CD31, ECadherin]
      - [CD68, ECadherin]
  meta:
    positive:
      - [CD45, CD3]
      - [CD45, CD20]
      - [CD45, CD68]
      - [pCK, CK5]
      - [pCK, CK7]
      - [pCK, CK8n18]
      - [pCK, CK19]
    negative:
      - [CD3, CD20]
      - [CD3, CD68]
      - [CD3, pCK]
      - [CD3, CD31]
      - [CD20, CD68]
      - [CD20, pCK]
      - [CD20, CD31]
      - [CD45, pCK]
      - [pCK, Vimentin]
  basel:
    positive:
      - [CD45, CD3]
      - [CD45, CD20]
      - [CD45, CD68]
      - [pCK, CK5]
      - [pCK, CK7]
      - [pCK, CK8n18]
      - [pCK, CK19]
    negative:
      - [CD3, CD20]
      - [CD3, CD68]
      - [CD3, pCK]
      - [CD3, CD31]
      - [CD20, CD68]
      - [CD20, pCK]
      - [CD20, CD31]
      - [CD45, pCK]
      - [pCK, Vimentin]
initial_algo:
  - PG
  - KM
  - GMM
  - FS

#hyperparameter_grid:
#  - lambda:
#    - 0.1
#    - 1.0
#    - 10.0
#  - cofactor:
#    - 0.1
#    - 1.0
#    - 10.0
