cohort: "tonsil"

k: 20 #20 means number of clusters
initial_clustering_method: "KM"
sample_size: 10 #10 meeans 10k samples & 30 means 30k samples
code_dir: '/home/campbell/yulee/project/starling'
#input_dir: "/home/campbell/yulee/project/starling/example_input"
#output_dir: '/home/campbell/yulee/project/starling/output'

cofactor: 1
model_regularizer: 1

dist: 2 #0 uses normal dist. & 2 uses t dist with df 2
model_overlap: 1 #0 models no cell overlap and and 1 otherwise
model_cell_size: 1 #0 implies cell sizes are not used and 1 otherwise